*REMARK*    PARENT_KEYWORD PARENT_VALUE
*REMARK*  [ { 
*REMARK*       CHILD_KEYWORD CHILD_VALUE
*REMARK*     [ CHILD_KEYWORD CHILD_VALUE
*REMARK*     [ { 
*REMARK*          GRAND_CHILD_KEYWORD GRAND_CHILD_VALUE [...] 
*REMARK*       } ]] 
*REMARK*    } ] 

DOCUMENTS_LIST PARENT
{
VERSION 1
DOCUMENT PDF
{
FOOTER1 0,0,
FOOTER2 0,1,
FOOTER3 0,2,
HEADER1 0,0,
HEADER2 0,1,
HEADER3 0,2,
CONFIG_NAME PDF Document
PAGE_SIZE 8,1,314972699,445770000
COLOR_MODE 1
BOOKMARK_MODE 2,0,0,0
STROKE_FONT ,0,0,0
POPUPS 0,0
PAGE 1
{
PAGE_NAME Composite
BOARD_OUTLINE 1
CONNECTIONS 0
THROUGH_HOLE 1,1
MIRROR_IMAGE 0
MIRROR_REFDES 0
OFFSET 0,0
SCALE 0
JUSTIFICATION 2
LAYER ${layer}
{
LAYER_NUMBER ${layer}
SMD_PADS 0
THORUGH_HOLE_PADS 1
TRACES 1
LINES 0
VIAS 1
COPPERS 1
HATCH_OUTLINES 1
POUR_OUTLINES 1
KEEPOUTS 0
REF_DES 0
PART_TYPES 0
TEXTS 0
ATTRIBUTES 0
COMPONENT_OUTLINES_TOP 0
COMPONENT_OUTLINES_BOTTOM 0
TEST_POINTS 0
PARTIAL_DRILLS 0
PIN_NUMBERS 0
MARKUPS 0
}
}
}
}
